baseURL = 'http://localhost'
languageCode = 'en-us'
title = '영국 개발자 그룹 UDG'
theme = "hugo-geekdoc"

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true
enableRobotsTXT = false

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode or when nesting shortcodes (e.g. img within
    # columns or tabs)
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

# for more information (visit)[https://geekdocs.de/usage/configuration/]
[params]
    geekdocDarkModeCode = true